services:
  - type: web
    name: ticketflow-twig
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: PHP_VERSION
        value: "8.1"